### ISSUE TITLE
ccmpred.c:529: error: ‘conjugrad_parameter_t’ has no member named ‘k’

### ISSUE THREAD

**Issue by kad-ecoli** [soedinglab/CCMpred#1]
[1] lib/libconjugrad was empty and cmake cannot proceed

[2] make complaint about ccmpred.c:529: error: ‘conjugrad_parameter_t’ has no member named ‘k’

**Comment by sseemayer** [comment]
Please make sure that the libconjugrad submodule is available by running the following commands mentioned in the README:

```
git submodule init
git submodule update
```
after that, you should be able to compile CCMpred with the correct libconjugrad version.

Alternatively, you can re-clone CCMpred using

```
git clone --recursive https://github.com/soedinglab/CCMpred.git
```

Please let me know if this works for you!

**Comment by sseemayer** [comment]
Since I haven't heard back, I'll assume that this solved the issue.
