### ISSUE TITLE
reading output

### ISSUE THREAD

**Issue by FloraMika** [soedinglab/CCMpred#13]
Hi,
CCMpred is running in my case but we have an issue:
We mentionned that in the output matrix have the dimention of the studied sequence + gaps. How is it possible that a score is calculated between a gap and a residue? From which residue can we considere the first amino acid?

I am waiting for your answer,

Best regards,

Flora

**Comment by FloraMika** [comment]
Dear @croth1, Thank you really much for your answer,
I manage to parse the output. I am trying to compare the best top coupling residues with a distance matrix of amino acids  to see if the top coupling correspond to distance < 8 A. I am still not sure how to obtain a final score (how to weight correct correlation).
Best regards,

Flora

**Comment by croth1** [comment]
> I am still not sure how to obtain a final score
The output file contains the matrix M[i,j] that is corrected with APC (see ccmpred -h). The values in M are your ranking scores.
There are different ways in the literature that is used to evaluate the quality of predictions. If you are interested it is best if you directly refer to the relevant papers.

Best,
Christian
