### ISSUE TITLE
libconjugrad empty

### ISSUE THREAD

**Issue by ever4cyth** [soedinglab/CCMpred#2]
CMake Error at CMakeLists.txt:159 (add_subdirectory):
   The source directory

     /home/immune/Downloads/CCMpred-master/lib/libconjugrad

   does not contain a CMakeLists.txt file.

**Comment by sseemayer** [comment]
Thanks for your interest in CCMpred! As mentioned in the [README](https://github.com/soedinglab/CCMpred#cloning-from-git), when cloning from git, it's important to also initialize and clone the libconjugrad submodule. Try running cmake again after running

```
git submodule init
git submodule update
```
