### ISSUE TITLE
Compiler issue?!

### ISSUE THREAD

**Issue by fsimkovic** [soedinglab/CCMpred#3]
I'm running into trouble installing CCMpred on Ubuntu 16.04 LTS. My `cmake` and `make` outputs are below.

Have you @sseemayer got any idea what the problem is? Thanks in advance! 

---
    $> cmake .
    "cmake" '.'
    + cmake .
    -- The C compiler identification is GNU 5.4.0
    -- The CXX compiler identification is GNU 5.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- MsgPack was not found. Make sure MSGPACK_LIBRARY and MSGPACK_INCLUDE_DIR are set.
    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
    -- Found LibJansson: /usr/lib/x86_64-linux-gnu/libjansson.so  
    -- Found LibUUID: /usr/lib/x86_64-linux-gnu/libuuid.so  
    -- Try OpenMP C flag = [-fopenmp]
    -- Performing Test OpenMP_FLAG_DETECTED
    -- Performing Test OpenMP_FLAG_DETECTED - Success
    -- Try OpenMP CXX flag = [-fopenmp]
    -- Performing Test OpenMP_FLAG_DETECTED
    -- Performing Test OpenMP_FLAG_DETECTED - Success
    -- Found OpenMP: -fopenmp  
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE  
    -- Found CUDA: /usr (found version "7.5") 
    -- Found Curses: /usr/lib/x86_64-linux-gnu/libcurses.so  
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /opt/CCMpred
---
    $> make
    "make"
    + make
    [  5%] Building NVCC (Device) object lib/libconjugrad/CMakeFiles/conjugrad.dir/src/conjugrad_generated_conjugrad_kernels.cu.o
    ptxas info    : 0 bytes gmem
    ptxas info    : Compiling entry function '_Z12vecdot_interPfS_S_i' for 'sm_20'
    ptxas info    : Function properties for _Z12vecdot_interPfS_S_i
        0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Used 14 registers, 60 bytes cmem[0]
    ptxas info    : Function properties for _Z14warp_reductionPVfi
        0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Compiling entry function '_Z12initialize_sPfS_i' for 'sm_20'
    ptxas info    : Function properties for _Z12initialize_sPfS_i
        0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Used 9 registers, 52 bytes cmem[0]
    ptxas info    : Compiling entry function '_Z13sum_reductionPfS_i' for 'sm_20'
    ptxas info    : Function properties for _Z13sum_reductionPfS_i
        0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Used 12 registers, 52 bytes cmem[0]
    ptxas info    : Compiling entry function '_Z8update_xPfS_ffi' for 'sm_20'
    ptxas info    : Function properties for _Z8update_xPfS_ffi
        0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Used 11 registers, 60 bytes cmem[0]
    ptxas info    : Function properties for _Z22sum_reduction_functionPVfi
        0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Compiling entry function '_Z8update_sPfS_fi' for 'sm_20'
    ptxas info    : Function properties for _Z8update_sPfS_fi
        0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Used 10 registers, 56 bytes cmem[0]
    Scanning dependencies of target conjugrad
    [ 10%] Building C object lib/libconjugrad/CMakeFiles/conjugrad.dir/src/conjugrad.c.o
    [ 15%] Building C object lib/libconjugrad/CMakeFiles/conjugrad.dir/src/debug.c.o
    [ 21%] Building C object lib/libconjugrad/CMakeFiles/conjugrad.dir/src/arithmetic_ansi.c.o
    [ 26%] Building C object lib/libconjugrad/CMakeFiles/conjugrad.dir/src/conjugrad_cuda.c.o
    [ 31%] Linking CXX static library libconjugrad.a
    [ 31%] Built target conjugrad
    [ 36%] Building NVCC (Device) object CMakeFiles/cuda_compile.dir/src/cuda_compile_generated_evaluate_cuda_kernels.cu.o
    Scanning dependencies of target ccmpred
    [ 42%] Building C object CMakeFiles/ccmpred.dir/src/ccmpred.c.o
    /opt/CCMpred/src/ccmpred.c: In function ‘main’:
    /opt/CCMpred/src/ccmpred.c:730:5: error: ‘msgpackfilename’ undeclared (first use in this function)
      if(msgpackfilename != NULL) {
         ^
    /opt/CCMpred/src/ccmpred.c:730:5: note: each undeclared identifier is reported only once for each     function it appears in
    CMakeFiles/ccmpred.dir/build.make:69: recipe for target 'CMakeFiles/ccmpred.dir/src/ccmpred.c.o' failed
    make[2]: *** [CMakeFiles/ccmpred.dir/src/ccmpred.c.o] Error 1
    CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ccmpred.dir/all' failed
    make[1]: *** [CMakeFiles/ccmpred.dir/all] Error 2
    Makefile:149: recipe for target 'all' failed
    make: *** [all] Error 2

**Comment by sseemayer** [comment]
Sorry about that @fsimkovic , this is a bug in the conditional compilation of CCMpred that occurs if the machine has libjansson installed but not libmsgpack - can you check if 414f467 fixes your problem?

**Comment by fsimkovic** [comment]
Thanks @sseemayer, that fixed the problem!
