### ISSUE TITLE
Cannot intall fatal error: jansson.h: No such file or directory

### ISSUE THREAD

**Issue by dxyzx0** [soedinglab/CCMpred#31]
```
CCMpred/src/ccmpred.c:17:0:
/path/DGraphDTA/CCMpred/include/meta.h:2:10: fatal error: jansson.h: No such file or directory
 #include "jansson.h"
          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/ccmpred.dir/src/ccmpred.c.o] Error 1
make[1]: *** [CMakeFiles/ccmpred.dir/all] Error 2
make: *** [all] Error 2
```
But I have installed both `jasson 2.13.1` and `jansson-devel`
And 
```
cmake version 3.18.2
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
```

**Comment by dxyzx0** [comment]
When executing `cmake .`
I got the following log:
```
-- MsgPack was not found. Make sure MSGPACK_LIBRARY and MSGPACK_INCLUDE_DIR are set.                                                                                                                                                                                                       
 -- Configuring done
 -- Generating done
 -- Build files have been written to: /path/CCMpred
```
But I have installed msgpack through `yum install msgpack`

**Comment by croth1** [comment]
Hi @DingXiangYuanZhiXing,
Can you give some extra information about the distribution you are using? If you are using yum to satisfy the dependencies, you will want to install jansson-devel and msgpack-devel.

**Comment by dxyzx0** [comment]
sorry, I don’t quite get your question. I’m using centos 7. Is that what you need?

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："Christian Roth "<notifications@github.com&gt;;
发送时间：2020年9月12日(星期六) 晚上6:21
收件人："soedinglab/CCMpred" <CCMpred@noreply.github.com&gt;;
抄送："DingXiangYuanZhiXing "<151120093@smail.nju.edu.cn&gt;;"Mention "<mention@noreply.github.com&gt;;
主题：Re: [soedinglab/CCMpred] Cannot intall fatal error: jansson.h: No such file or directory (#31)
-----------------------------------

 

 
Hi @DingXiangYuanZhiXing,
 Can you give some extra information about the distribution you are using? If you are using yum to satisfy the dependencies, you will want to install jansson-devel and msgpack-devel.

**Comment by croth1** [comment]
Yes, thanks. You will need to install [msgpack-devel](https://centos.pkgs.org/7/epel-x86_64/msgpack-devel-3.1.0-4.el7.x86_64.rpm.html) and [jansson-devel](https://centos.pkgs.org/7/centos-x86_64/jansson-devel-2.10-1.el7.x86_64.rpm.html) with yum.
If you are still getting errors after installing these two libraries, please start from fresh, post the `cmake` and `make` command you are using and the full output and I might be able to help you debug it.

**Comment by dxyzx0** [comment]
After I delete the whole folder and start with `git clone` again, I solved the bug. But I got the following warning
```
make
Scanning dependencies of target conjugrad
[  5%] Building C object lib/libconjugrad/CMakeFiles/conjugrad.dir/src/conjugrad.c.o
[ 10%] Building C object lib/libconjugrad/CMakeFiles/conjugrad.dir/src/debug.c.o
[ 15%] Building C object lib/libconjugrad/CMakeFiles/conjugrad.dir/src/arithmetic_ansi.c.o
[ 21%] Building C object lib/libconjugrad/CMakeFiles/conjugrad.dir/src/conjugrad_cuda.c.o
[ 26%] Building CUDA object lib/libconjugrad/CMakeFiles/conjugrad.dir/src/conjugrad_kernels.cu.o
[ 31%] Linking CUDA static library libconjugrad.a
[ 31%] Built target conjugrad
Scanning dependencies of target ccmpred
[ 36%] Building C object CMakeFiles/ccmpred.dir/src/ccmpred.c.o
[ 42%] Building C object CMakeFiles/ccmpred.dir/src/sequence.c.o
[ 47%] Building C object CMakeFiles/ccmpred.dir/src/util.c.o
[ 52%] Building C object CMakeFiles/ccmpred.dir/src/io.c.o
[ 57%] Building C object CMakeFiles/ccmpred.dir/src/evaluate_cpu.c.o
[ 63%] Building C object CMakeFiles/ccmpred.dir/src/parseopt.c.o
[ 68%] Building C object CMakeFiles/ccmpred.dir/src/reweighting.c.o
[ 73%] Building C object CMakeFiles/ccmpred.dir/src/numdif.c.o
[ 78%] Building C object CMakeFiles/ccmpred.dir/src/meta.c.o
[ 84%] Building C object CMakeFiles/ccmpred.dir/src/evaluate_cpu_omp.c.o
[ 89%] Building C object CMakeFiles/ccmpred.dir/src/evaluate_cuda.c.o
[ 94%] Building CUDA object CMakeFiles/ccmpred.dir/src/evaluate_cuda_kernels.cu.o
In file included from /path/CCMpred/src/evaluate_cuda_kernels.cu:3:0:
/usr/local/cuda-10.2/targets/x86_64-linux/include/math_functions.h:54:2: warning: #warning "math_functions.h is an internal header file and must not be used directly.  This file will be removed in a future CUDA release.  Please use cuda_runtime_api.h or cuda_runtime.h instead." [-Wcpp]
 #warning "math_functions.h is an internal header file and must not be used directly.  This file will be removed in a future CUDA release.  Please use cuda_runtime_api.h or cuda_runtime.h instead."
  ^
In file included from /path/CCMpred/src/evaluate_cuda_kernels.cu:3:0:
/usr/local/cuda-10.2/targets/x86_64-linux/include/math_functions.h:54:2: warning: #warning "math_functions.h is an internal header file and must not be used directly.  This file will be removed in a future CUDA release.  Please use cuda_runtime_api.h or cuda_runtime.h instead." [-Wcpp]
 #warning "math_functions.h is an internal header file and must not be used directly.  This file will be removed in a future CUDA release.  Please use cuda_runtime_api.h or cuda_runtime.h instead."
  ^
[100%] Linking CUDA executable bin/ccmpred
[100%] Built target ccmpred
```
Will the warning prevent me from using CUDA? Thank you very much!

**Comment by dxyzx0** [comment]
By the way, can I remove the folder after `make`?? Or I need to put `bin` folder somewhere else so the program can find it? Thank you very much!!

**Comment by croth1** [comment]
> Will the warning prevent me from using CUDA? Thank you very much!

It's just a warning. I don't think this will cause any problems.

> By the way, can I remove the folder after make?? Or I need to put bin folder somewhere else so the program can find it?

You have two options:
- either you keep the folder and start ccmpred out of this folder.
- you use `make install` to install it into a folder of your choice. (See also [this](https://stackoverflow.com/questions/6003374/what-is-cmake-equivalent-of-configure-prefix-dir-make-all-install) for how to set the folder). If you go with this option you can delete the build folder.
