### ISSUE TITLE
Libmsgpack issue

### ISSUE THREAD

**Issue by fsimkovic** [soedinglab/CCMpred#4]
Just to open a new thread for this issue. 

I've installed the libmsgpack library files with `apt-get install libmsgpack-dev` on Ubuntu 16.04 LTS. Running `cmake` again and `make` gives me the following outputs. 

Any suggested fix @sseemayer?

---
    $> cmake .
    "cmake" '.'
    + cmake .
    -- The C compiler identification is GNU 5.4.0
    -- The CXX compiler identification is GNU 5.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found these msgpack libs: /usr/lib/libmsgpack.so
    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
    -- Found LibJansson: /usr/lib/x86_64-linux-gnu/libjansson.so  
    -- Found LibUUID: /usr/lib/x86_64-linux-gnu/libuuid.so  
    -- Try OpenMP C flag = [-fopenmp]
    -- Performing Test OpenMP_FLAG_DETECTED
    -- Performing Test OpenMP_FLAG_DETECTED - Success
    -- Try OpenMP CXX flag = [-fopenmp]
    -- Performing Test OpenMP_FLAG_DETECTED
    -- Performing Test OpenMP_FLAG_DETECTED - Success
    -- Found OpenMP: -fopenmp  
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE  
    -- Found CUDA: /usr (found version "7.5") 
    -- Found Curses: /usr/lib/x86_64-linux-gnu/libcurses.so  
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /opt/CCMpred
---
    "make"
    + make
    [  5%] Building NVCC (Device) object lib/libconjugrad/CMakeFiles/conjugrad.dir/src/conjugrad_generated_conjugrad_kernels.cu.o
    ptxas info    : 0 bytes gmem
    ptxas info    : Compiling entry function '_Z12vecdot_interPfS_S_i' for 'sm_20'
    ptxas info    : Function properties for _Z12vecdot_interPfS_S_i
        0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Used 14 registers, 60 bytes cmem[0]
    ptxas info    : Function properties for _Z14warp_reductionPVfi
        0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Compiling entry function '_Z12initialize_sPfS_i' for 'sm_20'
    ptxas info    : Function properties for _Z12initialize_sPfS_i
        0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Used 9 registers, 52 bytes cmem[0]
    ptxas info    : Compiling entry function '_Z13sum_reductionPfS_i' for 'sm_20'
    ptxas info    : Function properties for _Z13sum_reductionPfS_i
        0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Used 12 registers, 52 bytes cmem[0]
    ptxas info    : Compiling entry function '_Z8update_xPfS_ffi' for 'sm_20'
    ptxas info    : Function properties for _Z8update_xPfS_ffi
        0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Used 11 registers, 60 bytes cmem[0]
    ptxas info    : Function properties for _Z22sum_reduction_functionPVfi
        0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Compiling entry function '_Z8update_sPfS_fi' for 'sm_20'
    ptxas info    : Function properties for _Z8update_sPfS_fi
        0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
    ptxas info    : Used 10 registers, 56 bytes cmem[0]
    Scanning dependencies of target conjugrad
    [ 10%] Building C object lib/libconjugrad/CMakeFiles/conjugrad.dir/src/conjugrad.c.o
    [ 15%] Building C object lib/libconjugrad/CMakeFiles/conjugrad.dir/src/debug.c.o
    [ 21%] Building C object lib/libconjugrad/CMakeFiles/conjugrad.dir/src/arithmetic_ansi.c.o
    [ 26%] Building C object lib/libconjugrad/CMakeFiles/conjugrad.dir/src/conjugrad_cuda.c.o
    [ 31%] Linking CXX static library libconjugrad.a
    [ 31%] Built target conjugrad
    [ 36%] Building NVCC (Device) object CMakeFiles/cuda_compile.dir/src/cuda_compile_generated_evaluate_cuda_kernels.cu.o
    Scanning dependencies of target ccmpred
    [ 42%] Building C object CMakeFiles/ccmpred.dir/src/ccmpred.c.o
    [ 47%] Building C object CMakeFiles/ccmpred.dir/src/sequence.c.o
    /opt/CCMpred/src/sequence.c: In function ‘read_msa’:
    /opt/CCMpred/src/sequence.c:73:3: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
       fgets(buf, SEQ_BUFFER, f);
       ^
    [ 52%] Building C object CMakeFiles/ccmpred.dir/src/util.c.o
    [ 57%] Building C object CMakeFiles/ccmpred.dir/src/io.c.o
    /opt/CCMpred/src/io.c: In function ‘write_raw_msgpack’:
    /opt/CCMpred/src/io.c:126:2: warning: implicit declaration of function ‘msgpack_pack_str’ [-Wimplicit-function-declaration]
      msgpack_pack_str(pk, 6);
      ^
    /opt/CCMpred/src/io.c:127:2: warning: implicit declaration of function ‘msgpack_pack_str_body’ [-Wimplicit-function-declaration]
      msgpack_pack_str_body(pk, "format", 6);
      ^
    /opt/CCMpred/src/io.c: In function ‘read_raw’:
    /opt/CCMpred/src/io.c:72:3: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
       fgets(line, 8192, f);
       ^
    /opt/CCMpred/src/io.c:81:4: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
        fgets(line, 8192, f);
        ^
    /opt/CCMpred/src/io.c:87:5: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
         fgets(line, 8192, f);
         ^
    [ 63%] Building C object CMakeFiles/ccmpred.dir/src/evaluate_cpu.c.o
    [ 68%] Building C object CMakeFiles/ccmpred.dir/src/parseopt.c.o
    [ 73%] Building C object CMakeFiles/ccmpred.dir/src/reweighting.c.o
    [ 78%] Building C object CMakeFiles/ccmpred.dir/src/numdif.c.o
    [ 84%] Building C object CMakeFiles/ccmpred.dir/src/meta.c.o
    /opt/CCMpred/src/meta.c: In function ‘json_object_to_msgpack’:
    /opt/CCMpred/src/meta.c:88:3: warning: implicit declaration of function ‘msgpack_pack_str’ [-Wimplicit-function-declaration]
       msgpack_pack_str(pk, strlen(key));
       ^
    /opt/CCMpred/src/meta.c:89:3: warning: implicit declaration of function ‘msgpack_pack_str_body’ [-Wimplicit-function-declaration]
       msgpack_pack_str_body(pk, key, strlen(key));
       ^
    [ 89%] Building C object CMakeFiles/ccmpred.dir/src/evaluate_cpu_omp.c.o
    [ 94%] Building C object CMakeFiles/ccmpred.dir/src/evaluate_cuda.c.o
    [100%] Linking C executable bin/ccmpred
    CMakeFiles/ccmpred.dir/src/io.c.o: In function `write_raw_msgpack':
    /opt/CCMpred/src/io.c:126: undefined reference to `msgpack_pack_str'
    /opt/CCMpred/src/io.c:127: undefined reference to `msgpack_pack_str_body'
    /opt/CCMpred/src/io.c:128: undefined reference to `msgpack_pack_str'
    /opt/CCMpred/src/io.c:129: undefined reference to `msgpack_pack_str_body'
    /opt/CCMpred/src/io.c:131: undefined reference to `msgpack_pack_str'
    /opt/CCMpred/src/io.c:132: undefined reference to `msgpack_pack_str_body'
    /opt/CCMpred/src/io.c:135: undefined reference to `msgpack_pack_str'
    /opt/CCMpred/src/io.c:136: undefined reference to `msgpack_pack_str_body'
    /opt/CCMpred/src/io.c:148: undefined reference to `msgpack_pack_str'
    /opt/CCMpred/src/io.c:149: undefined reference to `msgpack_pack_str_body'
    /opt/CCMpred/src/io.c:160: undefined reference to `msgpack_pack_str'
    /opt/CCMpred/src/io.c:161: undefined reference to `msgpack_pack_str_body'
    /opt/CCMpred/src/io.c:165: undefined reference to `msgpack_pack_str'
    /opt/CCMpred/src/io.c:166: undefined reference to `msgpack_pack_str_body'
    /opt/CCMpred/src/io.c:169: undefined reference to `msgpack_pack_str'
    /opt/CCMpred/src/io.c:170: undefined reference to `msgpack_pack_str_body'
    /opt/CCMpred/src/io.c:173: undefined reference to `msgpack_pack_str'
    /opt/CCMpred/src/io.c:174: undefined reference to `msgpack_pack_str_body'
    CMakeFiles/ccmpred.dir/src/meta.c.o: In function `json_string_to_msgpack':
    /opt/CCMpred/src/meta.c:107: undefined reference to `msgpack_pack_str'
    /opt/CCMpred/src/meta.c:107: undefined reference to `msgpack_pack_str'
    /opt/CCMpred/src/meta.c:108: undefined reference to `msgpack_pack_str_body'
    CMakeFiles/ccmpred.dir/src/meta.c.o: In function `json_object_to_msgpack':
    /opt/CCMpred/src/meta.c:88: undefined reference to `msgpack_pack_str'
    /opt/CCMpred/src/meta.c:89: undefined reference to `msgpack_pack_str_body'
    CMakeFiles/ccmpred.dir/src/meta.c.o: In function `json_string_to_msgpack':
    /opt/CCMpred/src/meta.c:107: undefined reference to `msgpack_pack_str'
    /opt/CCMpred/src/meta.c:108: undefined reference to `msgpack_pack_str_body'
    CMakeFiles/ccmpred.dir/src/meta.c.o: In function `meta_write_msgpack':
    /opt/CCMpred/src/meta.c:158: undefined reference to `msgpack_pack_str'
    /opt/CCMpred/src/meta.c:159: undefined reference to `msgpack_pack_str_body'
    CMakeFiles/ccmpred.dir/src/meta.c.o: In function `json_string_to_msgpack':
    /opt/CCMpred/src/meta.c:107: undefined reference to `msgpack_pack_str'
    /opt/CCMpred/src/meta.c:108: undefined reference to `msgpack_pack_str_body'
    /opt/CCMpred/src/meta.c:108: undefined reference to `msgpack_pack_str_body'
    collect2: error: ld returned 1 exit status
    CMakeFiles/ccmpred.dir/build.make:368: recipe for target 'bin/ccmpred' failed
    make[2]: *** [bin/ccmpred] Error 1
    CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ccmpred.dir/all' failed
    make[1]: *** [CMakeFiles/ccmpred.dir/all] Error 2
    Makefile:149: recipe for target 'all' failed
    make: *** [all] Error 2

**Comment by sseemayer** [comment]
MessagePack had an API change for string type names. The errors indicate that you're trying to compile CCMpred with an outdated MessagePack library.

**Comment by fsimkovic** [comment]
@sseemayer Which version number is required? I am currently using version ``0.5.7-3ubuntu1``.

**Comment by sseemayer** [comment]
Any version > 1.0 should be fine.

**Comment by fsimkovic** [comment]
Thanks for the Merge.
